export const CREATE_ORDER_REQUEST = 'CREATE_ORDER_REQUEST'
export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAILED = 'CREATE_ORDER_FAILED'

export const GET_ALL_ORDER_REQUEST = 'GET_ALL_ORDER_REQUEST'
export const GET_ALL_ORDER_SUCCESS = 'GET_ALL_ORDER_SUCCESS'
export const GET_ALL_ORDER_FAILED = 'GET_ALL_ORDER_FAILED'

export const CANCEL_ORDER_REQUEST = 'CANCEL_ORDER_REQUEST'
export const CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS'
export const CANCEL_ORDER_FAILED = 'CANCEL_ORDER_FAILED'

export const SEARCH_PRODUCTS_IN_ORDER_REQUEST = 'SEARCH_PRODUCTS_IN_ORDER_REQUEST'
export const SEARCH_PRODUCTS_IN_ORDER_SUCCESS = 'SEARCH_PRODUCTS_IN_ORDER_SUCCESS'
export const SEARCH_PRODUCTS_IN_ORDER_FAILED = 'SEARCH_PRODUCTS_IN_ORDER_FAILED'