

export const GET_ALL_PRODUCT_REQUEST = 'GET_ALL_PRODUCT_REQUEST'
export const GET_ALL_PRODUCT_SUCCESS = 'GET_ALL_PRODUCT_SUCCESS'
export const GET_ALL_PRODUCT_FAILED = 'GET_ALL_PRODUCT_FAILED'

export const GET_SINGLE_PRODUCT_REQUEST = 'GET_SINGLE_PRODUCT_REQUEST'
export const GET_SINGLE_PRODUCT_SUCCESS = 'GET_SINGLE_PRODUCT_SUCCESS'
export const GET_SINGLE_PRODUCT_FAILED = 'GET_SINGLE_PRODUCT_FAILED'

export const ADD_TO_WISHLIST_REQUEST = 'ADD_TO_WISHLIST_REQUEST'
export const ADD_TO_WISHLIST_SUCCESS = 'ADD_TO_WISHLIST_SUCCESS'
export const ADD_TO_WISHLIST_FAILED = 'ADD_TO_WISHLIST_FAILED'

export const GET_WISHLIST_REQUEST = 'GET_WISHLIST_REQUEST'
export const GET_WISHLIST_SUCCESS = 'GET_WISHLIST_SUCCESS'
export const GET_WISHLIST_FAILED = 'GET_WISHLIST_FAILED'

export const CHECK_IF_WISHLIST_REQUEST = 'CHECK_IF_WISHLIST_REQUEST'
export const CHECK_IF_WISHLIST_SUCCESS = 'CHECK_IF_WISHLIST_SUCCESS'
export const CHECK_IF_WISHLIST_FAILED = 'CHECK_IF_WISHLIST_FAILED'

export const DELETE_FROM_WISHLIST_REQUEST = 'DELETE_FROM_WISHLIST_REQUEST'
export const DELETE_FROM_WISHLIST_SUCCESS = 'DELETE_FROM_WISHLIST_SUCCESS'
export const DELETE_FROM_WISHLIST_FAILED = 'DELETE_FROM_WISHLIST_FAILED'

export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_FAILED = 'ADD_TO_CART_FAILED'

export const GET_CART_REQUEST = 'GET_CART_REQUEST'
export const GET_CART_SUCCESS = 'GET_CART_SUCCESS'
export const GET_CART_FAILED = 'GET_CART_FAILED'

export const SEARCH_PRODUCT_REQUEST = 'SEARCH_PRODUCT_REQUEST'
export const SEARCH_PRODUCT_SUCCESS = 'SEARCH_PRODUCT_SUCCESS'
export const SEARCH_PRODUCT_FAILED = 'SEARCH_PRODUCT_FAILED'

export const DELETE_PRODUCT_FROM_CART_REQUEST = 'DELETE_PRODUCT_FROM_CART_REQUEST'
export const DELETE_PRODUCT_FROM_CART_SUCCESS = 'DELETE_PRODUCT_FROM_CART_SUCCESS'
export const DELETE_PRODUCT_FROM_CART_FAILED = 'DELETE_PRODUCT_FROM_CART_FAILED'

export const ADD_RATING_REQUEST = 'ADD_RATING_REQUEST'
export const ADD_RATING_SUCCESS = 'ADD_RATING_SUCCESS'
export const ADD_RATING_FAILED = 'ADD_RATING_FAILED'


