# ADD PRODUCT
POST http://localhost:5000/public/products/add-product
Content-Type: application/json

{
   "title":"Harpa Women Maxi A-Line Dress",
   "description":"Closure Type: Tie; Material Composition: 100% Polyester; Department Name: Women; Occasion Type: Casual",
   "price": "694",
   "category":"Women",
   "featureimg":["https://m.media-amazon.com/images/I/613QQUEWx0L._UX679_.jpg","https://m.media-amazon.com/images/I/61g9FdfFEqL._UX679_.jpg"],
   "brand":"Harpa",
   "size":["S","M"],
    "color":["Blue"],
    "countInStock": 20,
    "type":"dresses",
    "metaTags":["women","dresses","casual"]
}

####
// GET ALL PRODUCTS
GET http://localhost:5000/public/products/all
Content-Type: application/json

###

// GET PRODUCT BY ID
GET http://localhost:5000/public/products/get-single-product/635a901388ec4d63160e3c9b
Content-Type: application/json

###

# ADD TO WISHLIST
POST http://localhost:5000/public/products/add-product-to-wishlist/64317a14f2a5ba39fe3682cf/635a901388ec4d63160e3c9b
Content-Type: application/json

###

# GET WISHLIST
GET http://localhost:5000/public/products/wishlist-products/6427e646c260690bd24a27ff
Content-Type: application/json

###

#REMOVE FROM WISHLIST
POST http://localhost:5000/public/products/remove-from-wishlist/64317a14f2a5ba39fe3682cf/635a901388ec4d63160e3c9b
Content-Type: application/json

###

#CHECK IN WISHLIST
GET http://localhost:5000/public/products/check-product-in-wishlist/64317a14f2a5ba39fe3682cf/635a901388ec4d63160e3c9b
Content-Type: application/json

###

# ADD TO CART
POST http://localhost:5000/public/products/add-to-cart/64317a14f2a5ba39fe3682cf/63666c85a9cd7e8bb75538f3

###

# add review
POST http://localhost:5000/public/products/add-review/63666c85a9cd7e8bb75538f3
Content-Type: application/json

{
    "userName":"John",
    "rating": 3,
    "comment": "average product"
}